perception: 
  _target_: pwc.perception.nu-mcc.PerceptionNUMCC
  config:
    ckpt_path: pwc/perception/numcc/pretrained/numcc_hypersim_550c.pth
    udf_threshold: 1.34
    visualize_pc: False
    floor: -0.8
    ceiling: -2

nav_sim:
  _target_: pwc.nav_sim.task_env.TaskEnv
  render: False
  config:
    mode: experiment # experiment or calibration
    room:
      room_dim: 8
      wall_thickness: 0.1
      wall_height: 4
      ground_rgba: [0.8, 0.8, 0.8, 1.0]
      wall_rgba: [0.9, 0.9, 0.9, 1.0]
    robot:
      half_dim: [0.323, 0.14, 0.2] 
      lidar_height: 0.15
      camera_thickness: 0.04
    dynamics:
      params_path: pwc/planning/sp_var.pkl
      dt: 0.1

    
#TODO 
calibration:
  _target_: pwc.calibration.PwC.PwC
  name: PwC
  calibration_dataset_base_path: /media/zm2074/Data Drive/data/perception-guarantees/PwC_calibration/calibrate_4k_rot/data/
  epsilon: 0.15
  delta: 0.01

experiment:
  _target_: pwc.experiments.occ_experiment.OccExperiment
  config:
    name: cpavg-numcc
    save_tag: _0603
    description: PWC calibration with 3DETR model
    visualize: False
    num_pc_points: 40000
    init_state: [0.5,-1,0,0]
    goal_loc: [7,-2, 0.5, 0]
    goal_loc_planner_frame: [6,7]
    cp: 1.34
    is_finetune: False
    num_envs: 100
    num_parallel: 10
    task: 
      path: /home/zm2074/Projects/data/perception-guarantees/task_1203_rot.pkl
      room_folder: /home/zm2074/Projects/data/perception-guarantees/room_1203_rot/
      goal_radius: 1.5
      init_state: [0.5, -1, 0, 0]
      observation:
        type: rgbd
        rgb:
          x_offset_from_robot_front: 0.05  # no y offset
          z_offset_from_robot_top: 0.8
          tilt: 0  # degrees of tilting down towards the floor
          img_w: 662
          img_h: 662
          aspect: 1.57
          fov: 70  # in PyBullet, this is vertical field of view in degrees
        depth:
          img_w: 662
          img_h: 376
        lidar:
          z_offset_from_robot_top: 0.01
          horizontal_res: 1  # resolution, in degree,1
          vertical_res: 1  # resolution, in degree , 1
          vertical_fov: 30  # half in one direction, in degree
          max_range: 5 # in meter Anushri changed from 5 to 8
        camera_pos: {}
        cam_not_inside_obs: {}
        is_visible: {}



planning:
  _target_: pwc.planning.occ_planner.OccPlanner
  map_size: [83,83]         # square grid map map_res pixels per side
  room_size: 8.0       # in meters
  n_samples: 4000      # will get overwritten if load samples
  r_n: 20.0
  path_resolution: 0.1
  sensor_dt: 0.5
  dt: 0.1
  rr: 1.0
  max_search_iter: 10000
  seed: 0
  Pset_path: /home/zm2074/Projects/perception-guarantees/backup/planning/pre_compute/Pset-4k.pkl
  reachable_path: /home/zm2074/Projects/perception-guarantees/backup/planning/pre_compute/reachable-4k.pkl
  verbose: False
