#TODO
perception: 
  type: bbox
  model: 3detr
  visualize: False
  num_pc_points: 40000
  num_chairs: 5
  num_boxes: 15
  room_thresholds:
    xmin: 0.05
    xmax: 7.95
    ymin: -3.9
    ymax: 3.9
    zmin: 0.1
    zmax: 2.9

environment:
  mode: calibration
  room:
    room_dim: 8
    wall_thickness: 0.1
    wall_height: 4
    ground_rgba: [0.8, 0.8, 0.8, 1.0]
    wall_rgba: [0.9, 0.9, 0.9, 1.0]
  robot:
    half_dim: [0.323, 0.14, 0.2] 
    lidar_height: 0.15
    camera_thickness: 0.04
  dynamics:
    params_path: ../pwc/planning/sp_var.pkl
    dt: 2
    
#TODO 
calibration:
  method: pwc
  calibration_dataset_base_path: /media/zm2074/Data Drive/data/perception-guarantees/PwC_calibration/calibrate_4k_rot/data/
  epsilon: 0.15
  delta: 0.01

#TODO
experiment:
  name: pwc-3detr
  description: PWC calibration with 3DETR model
  output_dir: outputs/pwc-3detr
  visualize: False
  num_pc_points: 40000
  init_state: [0,-3.5,0,0]
  goal_loc: [7.5,3.5]
